config.skyMap["discrete"].projection = "TAN"
config.skyMap["discrete"].raList = [320.332]
config.skyMap["discrete"].decList = [0.36]
config.skyMap["discrete"].radiusList = [1.4388796242707318]
config.skyMap["discrete"].rotation = 0.0
config.skyMap["discrete"].patchBorder = 100
config.skyMap["discrete"].tractOverlap = 0.0
config.skyMap["discrete"].pixelScale = 0.168
config.skyMap["discrete"].patchInnerDimensions = [2400, 2400]
config.skyMap.name = "discrete"
